name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI pipeline job
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Check maven version
        run: mvn --version
      - name: Run tests
        run: mvn test
