name: Workflow-1
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  print-nodejs-version:
    name: Print NodeJS version JOB
    runs-on: ubuntu-latest
    steps:
      - name: Print NodeJS version STEP
        run: node --version
  print-aws-version:
    name: Print AWS CLI version JOB
    runs-on: ubuntu-latest
    needs: [ print-nodejs-version ]
    steps:
      - name: Print AWS CLI version STEP
        run: aws --version
  print-java-version:
    name: Print Java version JOB
    runs-on: ubuntu-latest
    needs: [ print-aws-version ]
    steps:
      - name: Print Java version STEP
        run: java --version

